{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codex.fullname" . }}-secret
  labels:
    {{- include "codex.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
