replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "stable" 

service:
  type: ClusterIP
  port: 8080

podAnnotations: {}
  # linkerd.io/inject: enabled

env: []

networkPolicy:
  enabled: false
  ingress: []
