replicaCount: 1

image:
  repository: minio/minio
  tag: "latest"
  pullPolicy: IfNotPresent

rootUser: "minioadmin"
rootPassword: "minioadmin"

pvc:
  enabled: true
  size: "10Gi"

provisioning:
  enabled: true
  bucket: ""

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

podAnnotations: {}

notify:
  webhook:
    enabled: false
    identifier: "default"
    endpoint: ""
