replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "stable" 

service:
  type: ClusterIP
  http:
    enabled: true
    port: 8080
  grpc:
    enabled: false
    port: 8081

podAnnotations: {}

linkerd.io/inject: enabled

env: []

networkPolicy:
  enabled: false
  ingress: []

database:
  enabled: false
  env: []
