apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "minio.fullname" . }}-config
  labels:
    {{- include "minio.labels" . | nindent 4 }}
data:
  minio-api-port: "9000"
  minio-console-port: "9001"
