apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "minio.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: minio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              minio server /data \
                --console-address ":9001" \
                --address ":9000"
          ports:
            - name: api
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9001
              protocol: TCP
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}-secret
                  key: minio-root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}-secret
                  key: minio-root-password
            {{- if and .Values.notify.webhook.enabled .Values.notify.webhook.endpoint }}
            - name: MINIO_NOTIFY_WEBHOOK_ENABLE_{{ .Values.notify.webhook.identifier }}
              value: "on"
            - name: MINIO_NOTIFY_WEBHOOK_ENDPOINT_{{ .Values.notify.webhook.identifier }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}-secret
                  key: webhook-endpoint
            {{- end }}
          {{- if .Values.pvc.enabled }}
          volumeMounts:
            - name: minio-storage
              mountPath: /data
          {{- end }}
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: api
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: api
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.pvc.enabled }}
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: {{ include "minio.fullname" . }}-pvc
      {{- end }}
