apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-secret
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  minio-root-user: {{ .Values.rootUser | quote }}
  minio-root-password: {{ .Values.rootPassword | quote }}
  {{- if and .Values.notify.webhook.enabled .Values.notify.webhook.endpoint }}
  webhook-endpoint: {{ .Values.notify.webhook.endpoint | quote }}
  {{- end }}
